name: setting up environment

on: [push]
    
env:
 username: ElytrA8
jobs:
  build:
    runs-on: macos-latest

    steps:
       - name: Checkout
         uses: actions/checkout@main

       - name: initialization
         continue-on-error: true
         run: |
           git config --global user.name "ElytrA8"
           git config --global user.email "manofuranium@gmail.com"         
           brew install nodejs expect          
       - name: cloning repo & setting up config
         continue-on-error: true
         run: |
           git clone https://github.com/ElytrA8/shell-bot source
       - name: compilation
         continue-on-error: true
         run: |
           cd source
           npm install
       - name: running Bot
         timeout-minutes: 340
         continue-on-error: true
         run: |
           cd source
           node server          
       - name: Loop workflow
         continue-on-error: true
         run: |
              git clone https://github.com/$username/shellbot-workflow loop
              cd loop
              echo "1" >> loop.txt
              git add loop.txt
              git commit -m "Workflow : Loop"
              expect -c "
              spawn git push -f 
              expect \"Username\"
              send \"${{ secrets.GHUSER }}\r\"
              expect \"Password\"
              send \"${{ secrets.GHPASS }}\r\"
              expect \"main -> main\"
              set timeout -10
              interact"
              
